[build]
  command = """
    git clone https://github.com/flutter/flutter.git --depth 1 -b stable /tmp/flutter && \
    export PATH="/tmp/flutter/bin:$PATH" && \
    flutter config --enable-web && \
    cd mobile/billister_app && \
    flutter pub get && \
    flutter build web --release -t lib/main_prod.dart
  """
  publish = "mobile/billister_app/build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
